# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: moonconf
email: moonconf@maitria.com
description: > # this means to ignore newlines until "baseurl:"
  moonconf is a unconference put together quickly to provide a place for the
  functional programming community to learn and celebrate together. It's offered
  with love, and we'd love to see you there.
baseurl: ""
url: "http://moonconf.org"
twitter_username: moonconf
github_username:  maitria/moonconf.org

# Build settings
markdown: kramdown
